insert into words (title)
values ('Kyiv'),
       ('Lviv'),
       ('Lutsk'),
       ('Kharkiv'),
       ('Odesa'),
       ('Dnipro'),
       ('Amsterdam'),
       ('London'),
       ('Berlin'),
       ('Brussels'),
       ('Krakow'),
       ('Warsaw'),
       ('Zhytomyr'),
       ('Dusseldorf'),
       ('Stockholm'),
       ('Oslo'),
       ('Copenhagen'),
       ('Alchevs`k'),
       ('Avdiivka'),
       ('Paris'),
       ('Prague'),
       ('Budapest'),
       ('Vilnos')
